### ISSUE TITLE
blank white screen in android app

### ISSUE THREAD

**Issue by saza87** [cypherium/cypherium-wallet#10]
I try to reinstall but i does not help.

pls help

**Comment by rezaymd** [comment]
It doesn't work for me too
I tried different network's too...but it doesn't work yet😬

**Comment by jepson-zeng** [comment]
> I try to reinstall but i does not help.
> 
> pls help

The back end of the wallet was attacked and has now been fixed. I'm sorry for the trouble.

**Comment by jepson-zeng** [comment]
> It doesn't work for me too I tried different network's too...but it doesn't work yet😬

The back end of the wallet was attacked and has now been fixed. I'm sorry for the trouble.
