### ISSUE TITLE
Blank white screen in android cph wallet

### ISSUE THREAD

**Issue by rezaymd** [cypherium/cypherium-wallet#11]
I tried to reinstall the app but it doesn't work...
I tried to connect with other network's but it doesn't work...

**Comment by Seanseend** [comment]
Hello can someone help me i cant open the app nomore.. is there ny way to fix this.. thanx in advance

**Comment by jepson-zeng** [comment]
> I tried to reinstall the app but it doesn't work... I tried to connect with other network's but it doesn't work...

The back end of the wallet was attacked and has now been fixed. I'm sorry for the trouble.

**Comment by jepson-zeng** [comment]
> Hello can someone help me i cant open the app nomore.. is there ny way to fix this.. thanx in advance

The back end of the wallet was attacked and has now been fixed. I'm sorry for the trouble.

**Comment by jepson-zeng** [comment]
> Hello can someone help me i cant open the app nomore.. is there ny way to fix this.. thanx in advance

The back end of the wallet was attacked and has now been fixed. I'm sorry for the trouble.
