### ISSUE TITLE
Blank white screen

### ISSUE THREAD

**Issue by Mmmgggccc** [cypherium/cypherium-wallet#7]
Both myself (android user) and a friend of mine (apple user) are having issues with the wallet. 
When we open it up the wallet is just blank white. I cannot see the balance of my cph. 

I'm not worried, as I have my keys but is there an issue on the back end?

**Comment by jepson-zeng** [comment]
> Both myself (android user) and a friend of mine (apple user) are having issues with the wallet. When we open it up the wallet is just blank white. I cannot see the balance of my cph.
> 
> I'm not worried, as I have my keys but is there an issue on the back enzzz

> Both myself (android user) and a friend of mine (apple user) are having issues with the wallet. When we open it up the wallet is just blank white. I cannot see the balance of my cph.
> 
> I'm not worried, as I have my keys but is there an issue on the back end?

You're right. Sorry for the trouble. In the meantime, thank you for your feedback. The back end has been restarted and will be improved in the future.

**Comment by jepson-zeng** [comment]
> Both myself (android user) and a friend of mine (apple user) are having issues with the wallet. When we open it up the wallet is just blank white. I cannot see the balance of my cph.
> 
> I'm not worried, as I have my keys but is there an issue on the back end?
You're right. Sorry for the trouble. In the meantime, thank you for your feedback. The back end has been restarted and will be improved in the future.

**Comment by jepson-zeng** [comment]
> Both myself (android user) and a friend of mine (apple user) are having issues with the wallet. When we open it up the wallet is just blank white. I cannot see the balance of my cph.
> 
> I'm not worried, as I have my keys but is there an issue on the back end?


You're right！Sorry for the troubleIn the meantime, thank you for your feedback. The back end has been restarted and will be improved in the future.
